version: "3.3"

services:
  nginx-proxy:
    build: ./nginx
    ports:
      - "80:80"
    networks:
      - huis-flix-network
    extra_hosts:
      - huis-flix.nl:${HOST_IP}
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: movie_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - 3306:3306
    networks:
      - huis-flix-network
    volumes:
      - mysql_data:/var/lib/mysql

  adminer:
    image: adminer
    networks:
      - huis-flix-network
    links:
      - mysql
    ports:
      - 8888:8080

networks:
  huis-flix-network:

volumes:
  mysql_data:
